// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoDIACO.Data;

#nullable disable

namespace ProyectoDIACO.Migrations
{
    [DbContext(typeof(ProyectoDIACOContext))]
    [Migration("20220602022317_comerciosSucursales")]
    partial class comerciosSucursales
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProyectoDIACO.Models.Comercio", b =>
                {
                    b.Property<int>("ComercioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComercioId"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Telefono")
                        .HasMaxLength(8)
                        .HasColumnType("bigint");

                    b.HasKey("ComercioId");

                    b.ToTable("Comercio");
                });

            modelBuilder.Entity("ProyectoDIACO.Models.Sucursal", b =>
                {
                    b.Property<int>("SucursalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SucursalId"), 1L, 1);

                    b.Property<int>("ComercioId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.HasKey("SucursalId");

                    b.HasIndex("ComercioId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Sucursal");
                });

            modelBuilder.Entity("ProyectoDIACO.Models.Ubicacion", b =>
                {
                    b.Property<int>("UbicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UbicacionId"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SububicacionId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("UbicacionId");

                    b.ToTable("Ubicacion");

                    b.HasData(
                        new
                        {
                            UbicacionId = 1,
                            Nombre = "Suroccidente",
                            Tipo = 1
                        },
                        new
                        {
                            UbicacionId = 2,
                            Nombre = "Metropolitana",
                            Tipo = 1
                        },
                        new
                        {
                            UbicacionId = 3,
                            Nombre = "Noroccidente",
                            Tipo = 1
                        },
                        new
                        {
                            UbicacionId = 4,
                            Nombre = "Central",
                            Tipo = 1
                        },
                        new
                        {
                            UbicacionId = 5,
                            Nombre = "Verapaz",
                            Tipo = 1
                        },
                        new
                        {
                            UbicacionId = 6,
                            Nombre = "Nororiente",
                            Tipo = 1
                        },
                        new
                        {
                            UbicacionId = 7,
                            Nombre = "Suroriente",
                            Tipo = 1
                        },
                        new
                        {
                            UbicacionId = 8,
                            Nombre = "Petén",
                            Tipo = 1
                        },
                        new
                        {
                            UbicacionId = 9,
                            Nombre = "Quetzaltenango",
                            SububicacionId = 1,
                            Tipo = 2
                        },
                        new
                        {
                            UbicacionId = 10,
                            Nombre = "Guatemala",
                            SububicacionId = 2,
                            Tipo = 2
                        },
                        new
                        {
                            UbicacionId = 11,
                            Nombre = "Huehuetenango",
                            SububicacionId = 3,
                            Tipo = 2
                        },
                        new
                        {
                            UbicacionId = 12,
                            Nombre = "Chimaltenango",
                            SububicacionId = 4,
                            Tipo = 2
                        },
                        new
                        {
                            UbicacionId = 13,
                            Nombre = "Alta Verapaz",
                            SububicacionId = 5,
                            Tipo = 2
                        },
                        new
                        {
                            UbicacionId = 14,
                            Nombre = "Chiquimula",
                            SububicacionId = 6,
                            Tipo = 2
                        },
                        new
                        {
                            UbicacionId = 15,
                            Nombre = "Jutiapa",
                            SububicacionId = 7,
                            Tipo = 2
                        },
                        new
                        {
                            UbicacionId = 16,
                            Nombre = "Petén",
                            SububicacionId = 8,
                            Tipo = 2
                        },
                        new
                        {
                            UbicacionId = 17,
                            Nombre = "Quetzaltenango",
                            SububicacionId = 9,
                            Tipo = 3
                        },
                        new
                        {
                            UbicacionId = 18,
                            Nombre = "Guatemala",
                            SububicacionId = 10,
                            Tipo = 3
                        },
                        new
                        {
                            UbicacionId = 19,
                            Nombre = "Huehuetenango",
                            SububicacionId = 11,
                            Tipo = 3
                        },
                        new
                        {
                            UbicacionId = 20,
                            Nombre = "Chimaltenango",
                            SububicacionId = 12,
                            Tipo = 3
                        },
                        new
                        {
                            UbicacionId = 21,
                            Nombre = "Coban",
                            SububicacionId = 13,
                            Tipo = 3
                        },
                        new
                        {
                            UbicacionId = 22,
                            Nombre = "Chiquimula",
                            SububicacionId = 14,
                            Tipo = 3
                        },
                        new
                        {
                            UbicacionId = 23,
                            Nombre = "Jutiapa",
                            SububicacionId = 15,
                            Tipo = 3
                        },
                        new
                        {
                            UbicacionId = 24,
                            Nombre = "Flores",
                            SububicacionId = 16,
                            Tipo = 3
                        });
                });

            modelBuilder.Entity("ProyectoDIACO.Models.Usuario", b =>
                {
                    b.Property<int>("usuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("usuarioId"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Rol")
                        .HasColumnType("int");

                    b.HasKey("usuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ProyectoDIACO.Models.Sucursal", b =>
                {
                    b.HasOne("ProyectoDIACO.Models.Comercio", "Comercio")
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoDIACO.Models.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");

                    b.Navigation("Ubicacion");
                });
#pragma warning restore 612, 618
        }
    }
}
